name: flareline_uikit
description: "flareline_uikit"
version: 0.0.8
#homepage:

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_storage: ^2.1.1
  provider: ^6.1.2

  # Syncfusion (actualizados a 30.1.39)
  syncfusion_flutter_charts: ^30.1.39
  syncfusion_flutter_datagrid: ^30.1.39

  flutter_svg: ^2.0.14
  file_picker: ^8.1.4
  flutter_dropzone: ^4.2.0
  responsive_builder: ^0.7.1
  avatar_glow: ^3.0.1
  uuid: ^4.5.1
  logger: ^2.4.0
  rx_event_bus: ^2.0.1
  json_annotation: any
  window_location_href: ^1.0.1+2
  desktop_drop: ^0.5.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: any
  json_serializable: any

#flutter:
  # Puedes agregar assets si los necesitas
